### ISSUE TITLE
eXR GISO: CLI option can't override item in yaml file

### ISSUE THREAD

**Issue by skwsk** [ios-xr/gisobuild#26]
The below behaviour explained in README is not working

> To override any input in the yaml config file, please use the corresponding cli option and parameter.
> ```./src/gisobuild.py --yamlfile <input_yaml_cfg> --label <new_label>```
> The above command will override the label specified in yaml file with new option provided via cli option --label.

**Comment by cmohapat** [comment]
We will review and update here.

**Comment by pvpanda** [comment]
The fix you provided is incorrect. it will override everything in 'yaml_args' with whatever is in 'cli_args' including default values. for example:

in yaml:
pkglist: [x.rpm, y.rpm]

in cli:
gisobuild.py --yaml path/to/yaml/z.yaml

it will become something like as if you have passed:
pkglist: []

because [] is the default value if nothing is provided in the cli

The correct fix will be published soon.

**Comment by skwsk** [comment]
Not sure if it happen with the change I provided because the items in yaml to be override only if the same item in CLI args. In your example, pkglist is not in CLI args. Anyway, it seems you preparing fix so that's good. Looking forward to seeing the fix.
